#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:json", "json")
#@ load("@ytt:data", "data")

#@ stable_config = json.decode(data.values.stable_config)

apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
spec:
  #@overlay/match by="name",missing_ok=True
  region: #@ stable_config["region"]
  #@overlay/match by="name",missing_ok=True
  sshKeyName: #@ stable_config["ops_manager_key_pair_name"]
  #! Set to false to skip creation of bastion host
  bastion:
    #@overlay/match by="name",missing_ok=True
    enabled: false
  networkSpec:
    vpc:
      #@overlay/match by="name",missing_ok=True
      id: #@ stable_config["vpc_id"]